language: go
go:
- "1.10.2"
- tip
matrix:
  allow_failures:
  - go: master
branches:
  only:
  - develop
  - master
install:
  - go get github.com/keltia/cryptcheck
  - go get github.com/keltia/proxy
script:
  - go build -v ./...
  - go test -v ./...
