language: go
go:
- "1.10.x"
- tip
matrix:
  allow_failures:
  - go: master
branches:
  only:
  - develop
  - master
install:
  - go get github.com/keltia/proxy
  - go get github.com/keltia/observatory
  - go get github.com/keltia/cryptcheck
  - go get github.com/gobuffalo/packr
  - go get github.com/olekukonko/tablewriter
  - go get github.com/atotto/encoding/csv
script:
  - go build -v ./...
  - go test -v ./...
