language: go
go:
- "1.11.x"
- tip
matrix:
  allow_failures:
  - go: master
branches:
  only:
  - develop
  - master
env:
  - GO111MODULE=on
install:
  - go get github.com/gobuffalo/packr/...
script:
  - make
  - make test
