language: go
go:
- "1.11.x"
- tip
matrix:
  allow_failures:
  - go: master
branches:
  only:
  - develop
  - master
install:
  - GO111MODULE=yes go get github.com/gobuffalo/packr/...
script:
  - GO111MODULE=yes make
