language: go
go:
- "1.11.x"
- tip
matrix:
  allow_failures:
  - go: master
branches:
  only:
  - develop
  - master
script:
  - env GO111MODULE=yes go build -v ./...
  - env GO111MODULE=yes go test -v ./...
