language: go
go:
- 1.4
- 1.5.3
- 1.6.1
branches:
  only:
  - develop
  - master
install:
  - go get github.com/lib/pq
  - go get github.com/keltia/erc-checktls/imirhil
script:
  - go build
  - go test
